version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_app
      MYSQL_USER: budget_user
      MYSQL_PASSWORD: budget_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/budget_app
      SPRING_DATASOURCE_USERNAME: budget_user
      SPRING_DATASOURCE_PASSWORD: budget_pass

  frontend:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data: